// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYkgoBPrNP2R2WJM4c71_ihu1xNwIUx_A',
    appId: '1:980102022811:web:625153eed20c4c453d283e',
    messagingSenderId: '980102022811',
    projectId: 'practice-auth-e8c1e',
    authDomain: 'practice-auth-e8c1e.firebaseapp.com',
    storageBucket: 'practice-auth-e8c1e.firebasestorage.app',
    measurementId: 'G-RHF7L3H1SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfbAssTAfzbvlVPukIMz-uEKZNxFIGf2M',
    appId: '1:980102022811:android:60397edec73dccc43d283e',
    messagingSenderId: '980102022811',
    projectId: 'practice-auth-e8c1e',
    storageBucket: 'practice-auth-e8c1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4E5GeALJVpabSTF7JATCaLy5-9tHqIQ4',
    appId: '1:980102022811:ios:75468628b87ee3cd3d283e',
    messagingSenderId: '980102022811',
    projectId: 'practice-auth-e8c1e',
    storageBucket: 'practice-auth-e8c1e.firebasestorage.app',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4E5GeALJVpabSTF7JATCaLy5-9tHqIQ4',
    appId: '1:980102022811:ios:75468628b87ee3cd3d283e',
    messagingSenderId: '980102022811',
    projectId: 'practice-auth-e8c1e',
    storageBucket: 'practice-auth-e8c1e.firebasestorage.app',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYkgoBPrNP2R2WJM4c71_ihu1xNwIUx_A',
    appId: '1:980102022811:web:51c8272bab8f461b3d283e',
    messagingSenderId: '980102022811',
    projectId: 'practice-auth-e8c1e',
    authDomain: 'practice-auth-e8c1e.firebaseapp.com',
    storageBucket: 'practice-auth-e8c1e.firebasestorage.app',
    measurementId: 'G-S4R2PPGCF7',
  );
}
